### ISSUE TITLE
promises support

### ISSUE THREAD

**Issue by ricardofbarros** [atom/loophole#6]
Is there a way to support promises that I don't know?

**Comment by kevinsawicki** [comment]
What error are you seeing using them?

**Comment by ricardofbarros** [comment]
At first I was trying this approach and I wasn't getting much success.

``` js
return allowUnsafeNewFunction(function () { 
    var lintText = Q.nbind(standard.lintText, standard);
    var result = lintText(fileContent)

    return result
     .then(function () {
            ...
     })
     .catch(function () {
        ...
     })
})
```

The errors I was seeing was that I was still violating the CSP.
I have never been a promises aficionado guy, so I'm still learning how to use them correctly.

But then I tried a different approach. I used the `deferred` approach and it seems like I'm not getting more atom complaints about the CSP.

This was the final code.

``` js
return allowUnsafeNewFunction(function () {
    var deferred = Q.defer();

    standard.lintText(fileContent, function () {
        if (err) {
        return deferred.reject(err)
      }

        ...

        return deferred.resolve(stuff)

    })

    return deferred.promise;
});
```
